### ISSUE TITLE
gulp-web-compress

### ISSUE THREAD

**Issue by coreyfarrell** [Jimbly/modern-js#3]
I wrote/maintain gulp-web-compress.  I had planned on updating it to require node.js 13.x and provide ES modules only, but then I noticed that you are using it in a few repositories.  I'm willing to revert to CJS but only if this will help you stay updated.

The module be upgrading the `gulp-brotli` dependency so node.js `^10.16.0 || >=11.7.0` will be required even if I stick to CJS.  I'm not in a huge hurry to generate a new release but would appreciate your feedback.

**Comment by Jimbly** [comment]
Thanks for the consideration!

I generally only update my dependencies when I jump major Node versions, so as long as you appropriately bump the major version and I can still grab `0.x`, I don't see any major problem with it.  The current version of gulp-web-compress works just fine, so I don't expect needing any updates from you.

I'm generally a fan of CJS for node modules so things can keep running on old browsers and servers easily, but for a package only used in a gulpfile, I'm finding myself unable to come up with a single argument for it.

My projects/templates that use it are only used by 2-5 people, as far as I know (mostly for Ludum Dare entries and such, which will not generally ever get updated anyway ; ), so I wouldn't worry about it.

**Comment by coreyfarrell** [comment]
I'm actually planning to publish as 0.4.0, but note that 0.x versions are a bit different for semver-ranges.  You have your dependency listed as `^0.3.0`, this will not allow npm to install 0.4.0.

**Comment by Jimbly** [comment]
Ah, yeah, that's fine.

**Comment by coreyfarrell** [comment]
Thanks for responding.  I hope you enjoy the rest of your weekend!
